# version: '2'
# services:
#  web:
#    platform: linux/amd64
#    image: vulhub/php:8.1-backdoor
#    volumes:
#     - ./index.php:/var/www/html/index.php
#    ports:
#     - "8000:80"

version: '2'
services:
 web:
   image: vulhub/php:8.3.4-apache
   volumes:
    - ./index.php:/var/www/html/index.php
   ports:
     - "8080:80"
